SELECT * FROM ARTICLE ORDER BY DESIGNATION;
SELECT * FROM ARTICLE ORDER BY PRIX DESC;
SELECT * FROM ARTICLE WHERE DESIGNATION LIKE "boulon%" ORDER BY PRIX;
SELECT * FROM ARTICLE WHERE DESIGNATION LIKE "%sachet%";
SELECT * FROM ARTICLE WHERE DESIGNATION LIKE _utf8 "%SACHET%" COLLATE utf8_general_ci;

SELECT * FROM ARTICLE INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID ORDER BY FOURNISSEUR.NOM AND PRIX DESC;
SELECT * FROM ARTICLE INNER JOIN FOURNISSEUR ON ARTICLE.ID_FOU = FOURNISSEUR.ID WHERE FOURNISSEUR.NOM = "Dubois & Fils";
SELECT SUM(PRIX) FROM ARTICLE, FOURNISSEUR WHERE FOURNISSEUR.NOM = "Dubois & Fils" AND ARTICLE.ID_FOU = FOURNISSEUR.ID;
SELECT SUM(PRIX) FROM ARTICLE, FOURNISSEUR WHERE FOURNISSEUR.NOM = "FDM SA" AND ARTICLE.ID_FOU = FOURNISSEUR.ID;
SELECT SUM(PRIX) FROM ARTICLE, FOURNISSEUR WHERE FOURNISSEUR.NOM = "Française d'Imports" AND ARTICLE.ID_FOU = FOURNISSEUR.ID;
SELECT * FROM BON WHERE DATE_CMDE BETWEEN "2019-03-01" AND "2019-04-5 12:00:00";