SET SQL_SAFE_UPDATES = 0;
UPDATE ARTICLE SET DESIGNATION = UPPER(DESIGNATION) WHERE PRIX > 10;
UPDATE ARTICLE SET DESIGNATION = LOWER(DESIGNATION) WHERE ID = 2;
UPDATE ARTICLE SET PRIX = PRIX * 1.1 WHERE ID_FOU = 2;